### ISSUE TITLE
Posting a link to an video source won't show content

### ISSUE THREAD

**Issue by Genfood** [CreatureSurvive/Arctic-Issues#13]
Creating a new post, with a URL to video source, won't show the URL content in any way.
![image](https://github.com/CreatureSurvive/Arctic-Issues/assets/11618226/ba684787-e4ab-4fc0-b117-5cafe929a360)

The same happens if I click on the post via my profile page, in the profile feed the post ist visible but after taping on it the content disappeared. 

https://github.com/CreatureSurvive/Arctic-Issues/assets/11618226/c0337a2e-ce80-4598-8027-8900e28be18d

I would expect the content of the URL to be visible, or even better show the video.

Further more it seems to be buggy from time to time in the Community feed.

![image](https://github.com/CreatureSurvive/Arctic-Issues/assets/11618226/6a30a1e1-28f5-4689-a146-ac8803d3d431)

I guess something regarding the video loader is wrong here, because sometimes the videos do appear:

![image](https://github.com/CreatureSurvive/Arctic-Issues/assets/11618226/02fb9a1b-ce5b-4c33-bcd9-d88c7c0f2877)

After some time the video becomes visible. Maybe an indicator would be handy, or showing the first frame of the video, with an activity indicator. Something where I can tap on and the video playback screen will be shown.

**Comment by CreatureSurvive** [comment]
This one took me a while to track down. I've noticed this issue at seemingly random times for quite a while now, though I was unsure what was causing it. Well I finally figured it out, and it was a very simple fix. There should be no more issues with videos displaying with incorrect size after todays update (v0.4.0.8).

**Comment by Genfood** [comment]
I have the newest TestFlight build and the problem persists, after posting a link to a video. The view which appears right after posting the link to the video, will not show the video view, just the header and the body text.

![image](https://github.com/CreatureSurvive/Arctic-Issues/assets/11618226/f67b5316-5821-4b4f-9b69-f10bbcea3858)

The video content seems to visible just for a pixel or so in the top between navigation bar and page.

**Comment by Genfood** [comment]
The same happens if I open a notification to a video:

https://github.com/CreatureSurvive/Arctic-Issues/assets/11618226/eb2a29d7-2269-4f1e-a26e-b5a0da54b73e
