### ISSUE TITLE
[Bug]: iPad mode doesn’t remember sidebar toggle status after screen rotation.

### ISSUE THREAD

**Issue by villiansv** [CreatureSurvive/Arctic-Issues#14]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

To reproduce:

1. Run Arctic in iPad mode. This shows the sidebar, with the button to toggle it top left
2. Hit the button to hide the sidebar.
3. Rotate iPad from portrait to landscape, or vice versa. The sidebar is back.

ipados: 17.3.1 latest official

### Expected Behavior

The sidebar should stay hidden until manually toggled again via the top left button.

### Version

V0.3.2.3

### iOS Version

17.x Beta

### Device

iPad Pro (12.9-inch) (5th generation)

**Comment by CreatureSurvive** [comment]
Sorry for the delay in getting to this. I finally got around to resolving this in the latest release v0.4.0.7.
