### ISSUE TITLE
[Bug] Dropdown UI appears broken

### ISSUE THREAD

**Issue by youenjoi** [CreatureSurvive/Arctic-Issues#17]
**Description:**
Not totally sure if I'm explaining this correctly, but it seems that when a post uses a dropdown to create a table/list the formatting gets a bit wonky. 

For context, I'll include some screenshots of the bug on Arctic, and then how the dropdowns are appearing on Voyager. A good example of a post using this formatting is the Lemmy Apps megathread [here](https://lemmy.world/post/13129663).

**Arctic:** 
![image](https://github.com/CreatureSurvive/Arctic-Issues/assets/137808771/34765dbf-022f-4a55-b6f8-8380c7ece249)

![image](https://github.com/CreatureSurvive/Arctic-Issues/assets/137808771/a395fb78-4b0b-4702-a37a-54741c5ca5cb)

**Voyager:**
![image](https://github.com/CreatureSurvive/Arctic-Issues/assets/137808771/f24c2b97-065b-4fe0-81fe-200bc5696ce6)

![image](https://github.com/CreatureSurvive/Arctic-Issues/assets/137808771/84b45792-011a-4422-aa56-874e19ce4a64)

**Comment by CreatureSurvive** [comment]
I released v0.4.1.0 TestFlight build yesterday that resolves these issues with spoiler dropdowns not hiding all elements while collapsed. I also added basic support for markdown tables. That megathread post now displays correctly in Arctic. 

![megathread](https://github.com/CreatureSurvive/Arctic-Issues/assets/5193275/6f2d5ce3-4b9b-4f08-a491-76443a1dc7fa)

**Comment by youenjoi** [comment]
Awesome, just saw the update! Looks great, thanks!
