### ISSUE TITLE
Support of iOS-Share-Functionality

### ISSUE THREAD

**Issue by Ralph1798** [CreatureSurvive/Arctic-Issues#18]
Would be highly appreciated.

**Comment by CreatureSurvive** [comment]
In what context are you looking for share options? Sharing posts and media is already supported, I do need to add support for sharing comments, communities, and users. Is there something in particular you are looking to be able to share?

You can also open Lemmy links from anywhere in iOS using the share sheet if that is what you are looking for.

**Comment by Ralph1798** [comment]
I would like to share a link with the share-button in Safari.

Also "open in Arctic" just produces a white page showing the word "Label" for me.

**Comment by CreatureSurvive** [comment]
Okay, I think see what you mean. You want to be able to share links from safari, and have Arctic open the link in the post composer so you can post it to lemmy?

I can add that in, currently the _Open in Arctic_ extension only supports opening links to Lemmy posts, comments, communities, users, etc. I’ll update it to show an error if the link is invalid. I’ll also add a _Share with Arctic_ extension to open any link in the post composer.
