### ISSUE TITLE
Share button / context menu button disappears after swiping in image viewer

### ISSUE THREAD

**Issue by Genfood** [CreatureSurvive/Arctic-Issues#2]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

1. tap on a post with multiple images to view one image
2. Swipe in the image viewer 
3. The share button and the three dots for the context menu are only visible on the first views image

https://github.com/CreatureSurvive/Arctic-Issues/assets/11618226/aee23a82-1ee2-4028-955c-a8cbd5f3615a

[Example post](https://feddit.de/post/2809635)

### Expected Behavior

The buttons should be visible at all images.

### Version

0.2.5

### iOS Version

16.x

### Device

iPhone 12 Pro Max

**Comment by CreatureSurvive** [comment]
I have this fixed for the next release, I should be pushing the update out tonight.

I'll leave this open until the update is out.
