### ISSUE TITLE
Scrolling on desktop causes bar to unpin from bottom

### ISSUE THREAD

**Issue by superterran** [CreatureSurvive/Arctic-Issues#21]
### Check for open issues

- [ ] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

Open in MacOS, ensure the window is  fairly wide i.e. wider than 1100px, and begin to scroll through posts or comments, as you scroll the bar will begin to migrate upward. Resizing the window re-pins it to the bottom

### Expected Behavior

Bar should always be on the bottom of the window

### Version

0.4.1

### iOS Version

17.x Beta

### Device

MacOS on an MacBook Air M3

**Comment by CreatureSurvive** [comment]
This is fixed as of v0.4.2.0
