### ISSUE TITLE
Unsubscribe icon is misleading

### ISSUE THREAD

**Issue by Genfood** [CreatureSurvive/Arctic-Issues#3]
The unsubscribe icon looks like an icon for create a new post or something, maybe something different would be better here.  
At least I mistook it a few times as I wanted to create a post and suddenly unsubscribed instead.

![image](https://github.com/CreatureSurvive/Arctic-Issues/assets/11618226/1b0bed79-0a61-4dc9-a2f5-0f2341afc3ef)

**Comment by CreatureSurvive** [comment]
Good catch, I'll update this to be consistent with the community menu in the posts feed, as that one displays the correct images.

**Comment by CreatureSurvive** [comment]
This has been resolved, the menu icons are now consistent with other menus.
