### ISSUE TITLE
After a failed attempt to create a post activity indicator keeps spinning

### ISSUE THREAD

**Issue by Genfood** [CreatureSurvive/Arctic-Issues#5]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

1. Create a new post
2. Click on post without having a title e.g.
3. Error toast message appears and the post button disappears and an activity indicator keeps spinning at this position

https://github.com/CreatureSurvive/Arctic-Issues/assets/11618226/19f0dc6d-240c-4015-ae9a-69d8d6e9ba16

### Expected Behavior

After an error the post button should appear again.

### Version

0.2.5

### iOS Version

17.x Beta

### Device

iPhone 12 Pro Max

**Comment by CreatureSurvive** [comment]
Submitting a post will now warn you if your input is invalid prior to submitting it. Also, if a post fails to submit, the post button will be restored so you can edit, or try again.
