### ISSUE TITLE
Submitting a post is time-consuming

### ISSUE THREAD

**Issue by Genfood** [CreatureSurvive/Arctic-Issues#6]
Submitting a post has become unintuitive and time consuming. I would expect that the current community is preselected.

Also searching for a community is time-consuming. Maybe it is a good idea to show subscribed communities first, and sort the results by relevance (subscriber count...?).

I currently can't submit a screen recording of it but it takes ages to find `memes@lemmy.world`.

**Comment by CreatureSurvive** [comment]
This is great feedback. Submitting a post using the action menu (…) while browsing a community, will preselect the community when opening the post composer. I didn't add support for this contextual awareness when using the long press gesture on the tab bar.

As for the community selector search, it is slow, and doesn't support searching full community names eg(memes@lemmy.world). 

I will add contextual support for the long press gesture so it preselects the open community. For the community search, I'll update this to search while typing, and support full community names. I will add support for filtering community search results by (subscribed, local, all) and provide options to choose your default search type. 

Thanks for the feedback!

**Comment by CreatureSurvive** [comment]
This has been fixed as of v0.2.8. I was not able to add support for search while typing just yet. I'll add support for this in a future release when I implement caching for responses so as not to spam Lemmy with requests.
